# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-01 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(1, 'Borrower'), (2, 'Loan Officier')], default=1)),
                ('uuid', models.UUIDField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(max_length=20)),
                ('home_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uuid', models.UUIDField(unique=True)),
                ('previous_question_id', models.CharField(blank=True, max_length=50, null=True)),
                ('current_question_id', models.CharField(blank=True, max_length=50, null=True)),
                ('questionnaire_track', models.TextField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Inprogress'), (1, 'Completed'), (2, 'Submitted'), (3, 'Deleted')], default=0)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='app_questionnaires.CustomUser')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='app_questionnaires.CustomUser')),
                ('loan_officier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_officier', to='app_questionnaires.CustomUser')),
            ],
        ),
    ]
