# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_uuid',
            field=models.CharField(max_length=100),
        ),
    ]
